### ISSUE TITLE
Anonymization of (6000, 3000) Overlay Data

### ISSUE THREAD

**Issue by guozhaowang** [KitwareMedical/dicom-anonymizer#25]
Dear all,

Here is my DICOM file:
https://sourceforge.net/p/gdcm/gdcmdata/ci/2bddc5695f2482ee3f4d92db7de2348b816fe64c/tree/MR-SIEMENS-DICOM-WithOverlays.dcm

I run:
dicom-anonymizer MR-SIEMENS-DICOM-WithOverlays.dcm output.dcm

I got these error messages:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 763, in get
    key = Tag(key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/tag.py", line 79, in Tag
    raise ValueError("Tag must be an int or a 2-tuple")
ValueError: Tag must be an int or a 2-tuple

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/tag.py", line 28, in tag_in_exception
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 2216, in walk
    callback(self, data_element)  # self = this Dataset
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 387, in range_callback
    action(dataset, tag)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 164, in delete
    element = dataset.get(tag)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 765, in get
    raise TypeError("Dataset.get key must be a string or tag") from exc
TypeError: Dataset.get key must be a string or tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/dicom-anonymizer", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/anonymizer.py", line 161, in main
    anonymize(input_path, output_path, new_anonymization_actions, not args.keepPrivateTags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/anonymizer.py", line 50, in anonymize
    anonymize_dicom_file(input_files_list[cpt], output_files_list[cpt], anonymization_actions, deletePrivateTags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 295, in anonymize_dicom_file
    anonymize_dataset(dataset, extra_anonymization_rules, delete_private_tags)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 393, in anonymize_dataset
    dataset.walk(range_callback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 2222, in walk
    dataset.walk(callback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/tag.py", line 32, in tag_in_exception
    raise type(exc)(msg) from exc
TypeError: With tag (6000, 3000) got exception: Dataset.get key must be a string or tag
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 763, in get
    key = Tag(key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/tag.py", line 79, in Tag
    raise ValueError("Tag must be an int or a 2-tuple")
ValueError: Tag must be an int or a 2-tuple

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/tag.py", line 28, in tag_in_exception
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 2216, in walk
    callback(self, data_element)  # self = this Dataset
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 387, in range_callback
    action(dataset, tag)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dicomanonymizer/simpledicomanonymizer.py", line 164, in delete
    element = dataset.get(tag)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydicom/dataset.py", line 765, in get
    raise TypeError("Dataset.get key must be a string or tag") from exc
TypeError: Dataset.get key must be a string or tag

Plese help, thank you.

**Comment by pchoisel** [comment]
Hi @guozhaowang 

Sorry for this inconvenience.

I had a look, the problem seems to come from the way we handle "repeating group" DICOM tags.
More specifically, from the line https://github.com/KitwareMedical/dicom-anonymizer/blob/master/dicomanonymizer/simpledicomanonymizer.py#L387.
We should not try to apply actions on a 4-tuple tag without bringing it back to a 2-tuple tag.

I don't have the time right now to try to push a fix, but I'll be able next week.
In the mean time, feel free to have a look.

Have a great day,
Paul
