### ISSUE TITLE
VR IS not yet implemented

### ISSUE THREAD

**Issue by dmd** [KitwareMedical/dicom-anonymizer#37]
I'm seeing this:

```
$ dicom-anonymizer E29171854 anons
  1%|▌                                                                                               | 75/13460 [00:10<32:50,  6.79it/s]
Traceback (most recent call last):
  File "/cm/shared/anaconda3/bin/dicom-anonymizer", line 33, in <module>
    sys.exit(load_entry_point('dicom-anonymizer==1.0.9', 'console_scripts', 'dicom-anonymizer')())
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/anonymizer.py", line 175, in m
ain
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/anonymizer.py", line 64, in an
onymize
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/simpledicomanonymizer.py", lin
e 305, in anonymize_dicom_file
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/simpledicomanonymizer.py", lin
e 413, in anonymize_dataset
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/simpledicomanonymizer.py", lin
e 236, in delete_or_empty_or_replace_UID
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/simpledicomanonymizer.py", lin
e 142, in empty_element
  File "/cm/shared/anaconda3/lib/python3.9/site-packages/dicom_anonymizer-1.0.9-py3.9.egg/dicomanonymizer/simpledicomanonymizer.py", lin
e 144, in empty_element
NotImplementedError: Not anonymized. VR IS not yet implemented.
  1%|▌
```

What can we do about this?

**Comment by pchoisel** [comment]
Hi @dmd,

dicom-anonymizer does not know how to anonymize the VR IS.

Do you know what tag raises this error ? The behavior of dicom-anonymizer is to only modify the tags listed in dicomfields.py so I'm surprised it tries to anonymize a VR it doesn't know.

In any case, if possible, could you provide us the file that raises this error ?

**Comment by dmd** [comment]
Please contact me by email at dmd@3e.org and I'll get it to you.

**Comment by dmd** [comment]
Sent!

**Comment by pchoisel** [comment]
Hi @dmd,

This PR: https://github.com/KitwareMedical/dicom-anonymizer/pull/38 should have fixed your problem.  
Can you confirm ?

Thanks,

**Comment by dmd** [comment]
Fixed! Thank you!
